(("default" . ((user-emacs-directory . "~/repos/my-emacs")
               (server-name . "gnu")))
 ("doom" . ((user-emacs-directory . "~/repos/doom-emacs")
            (server-name . "doom")
            (env . (("DOOMDIR" . "~/.doom.d")))))
 ("centaur" . ((user-emacs-directory . "~/repos/centaur-emacs")
               (server-name . "centaur")))
 ("nano" . ((user-emacs-directory . "~/repos/nano-emacs"))))
