#!/usr/bin/env bash

PROGRAM_NAME="emacs"
REPOS_DIR="$HOME/repos"
BRANCH="emacs-29"
PROGRAM_REPO_URL="https://git.savannah.gnu.org/git/emacs.git"

if [[ $# -gt 0 ]]; then
  BRANCH=$1
fi

OLD_DIR=$(pwd)
if [[ -d "$REPOS_DIR/$PROGRAM_NAME" ]]; then
  update-repo "$REPOS_DIR/$PROGRAM_NAME" "$BRANCH"
else
  clone-repo "$PROGRAM_REPO_URL" "$REPOS_DIR" "$REPOS_DIR/$PROGRAM_NAME" "$BRANCH"
fi

[ $? -eq 0 ] && run-autogen "$PROGRAM_NAME"
[ $? -eq 0 ] && run-configure "$PROGRAM_NAME" "--with-rsvg"
[ $? -eq 0 ] && run-make "$PROGRAM_NAME"
[ $? -eq 0 ] && run-make-install "$PROGRAM_NAME"

cd "$OLD_DIR" || return
# EOF
