#!/usr/bin/env bash

# common init params ##########################################################
[[ -e "$HOME/.localrc" ]] && source "$HOME/.localrc"
[ $JITSI_PREFIX ] || JITSI_PREFIX="https://jitsi.org"
[ $JITSI_VISIO_LIST] || JITSI_VISIO_LIST="$HOME/.jitsi_visio_list"

call_jitsi(){
  room_name=$1
  echo room: $room_name
  echo room list: $JITSI_VISIO_LIST

  echo "$room_name" >> "$JITSI_VISIO_LIST"
  sort -u $JITSI_VISIO_LIST -o $JITSI_VISIO_LIST
  /usr/bin/google-chrome-stable --new-window %U --app="$JITSI_PREFIX/$room_name"
}

# jitsi kill
if [[ $# == 1  && $1 -eq "kill" ]]; then
  $(pkill -f $JITSI_PREFIX)
  exit 0
fi

# jitsi with rofi
if [[ $# == 1  && $1 -eq "rofi" ]]; then
  rofi-jitsi.sh
fi
CLIP=$(greenclip print | head -1)
call_jitsi ${CLIP#$JITSI_PREFIX/}
exit 0
