#!/usr/bin/env bash

sudo true
if hash snap 2>/dev/null; then
  make-title "snap refresh"
  sudo snap refresh
fi
if hash flatpak 2>/dev/null; then
  make-title "flatpak update"
  sudo flatpak update
fi

if hash pip 2>/dev/null; then
  make-title "python packages update"
  pip freeze --user | cut -d'=' -f1 | xargs -n1 pip install -U
fi

if hash aptitude 2>/dev/null; then
  make-title "aptitude update"
  sudo aptitude update
  make-title "aptitude upgrade"
  sudo aptitude full-upgrade -y
  make-title "aptitude auto-clean"
  sudo aptitude autoclean -y
  make-title "apt autoremove"
fi
if hash apt 2>/dev/null; then
  sudo apt autoremove -y
fi
notify-send "Upgrade complete!"
# EOF
