#!/usr/bin/env bash

sudo true
if hash snap 2>/dev/null; then
  make-title "snap refresh"
  sudo snap refresh
fi
if hash flatpak 2>/dev/null; then
  make-title "flatpak update"
  sudo flatpak update
fi

make-title "python packages update"
if hash pipx 2>/dev/null; then
  pipx upgrade-all
elif hash pip 2>/dev/null; then
  echo "[Python] pipx is not installed, trying pip."
  if pip 2>/dev/null && $? == 0; then
    pip freeze --user | cut -d'=' -f1 | xargs -n1 pip install -U
  else
    echo "[Python] error while updating pip packages."
  fi
else
  echo "[Python] pip is not properly installed."
fi

if hash aptitude 2>/dev/null; then
  make-title "aptitude update"
  sudo aptitude update
  make-title "aptitude upgrade"
  sudo aptitude full-upgrade -y
  make-title "aptitude auto-clean"
  sudo aptitude autoclean -y
  make-title "apt autoremove"
fi
if hash apt 2>/dev/null; then
  sudo apt autoremove -y
fi
notify-send "Upgrade complete!"
# EOF
