#!/usr/bin/env bash

sudo true
if hash snap 2>/dev/null; then
  make_title "snap refresh"
  sudo snap refresh

  #Removes old revisions of snaps
  LANG=en_US.UTF-8 snap list --all \
    | awk '/disabled/{print $1, $3}' \
    | while read snapname revision; do
    sudo snap remove "$snapname" --revision="$revision"
  done
fi

if hash flatpak 2>/dev/null; then
  make_title "flatpak update"
  flatpak uninstall --unused
  # sudo rm -rfv /var/tmp/flatpak-cache-*
  sudo flatpak update
fi

make_title "python packages update"
if hash pipx 2>/dev/null; then
  pipx upgrade-all
elif hash pip 2>/dev/null; then
  echo "[Python] pipx is not installed, trying pip."
  if pip 2>/dev/null && $? == 0; then
    pip freeze --user | cut -d'=' -f1 | xargs -n1 pip install -U
  else
    echo "[Python] error while updating pip packages."
  fi
else
  echo "[Python] pip is not properly installed."
fi

if hash aptitude 2>/dev/null; then
  make_title "aptitude update"
  sudo aptitude update
  make_title "aptitude upgrade"
  sudo aptitude full-upgrade -y
  make_title "aptitude auto-clean"
  sudo aptitude autoclean -y
  make_title "apt autoremove"
fi
if hash apt 2>/dev/null; then
  sudo apt autoremove -y
fi

make_title "disk usage"
df -ht ext4

notify-send "Upgrade complete!"
# EOF
