#!/usr/bin/env bash
OLD_DIR=$(pwd)
cd ~/repos/emacs
git fetch --all
# git checkout feature/native-comp
git checkout master
git pull
echo "****************************************************"
echo "****************************************************"
./autogen.sh
echo "****************************************************"
echo "****************************************************"
# ./configure --with-nativecomp
./configure
echo "****************************************************"
echo "****************************************************"
make -j4
echo "****************************************************"
echo "****************************************************"
sudo make install
cd $OLD_DIR
# EOF
