#!/usr/bin/env bash
OLD_DIR=$(pwd)
cd ~/repos/emacs
git fetch --all
# git checkout feature/native-comp
git checkout master
git pull
echo "****************************************************"
echo "****************************************************"
./autogen.sh
echo "****************************************************"
echo "****************************************************"
./configure --with-native-compilation
echo "****************************************************"
echo "****************************************************"
make -j$(nproc)
echo "****************************************************"
echo "****************************************************"
sudo make install
cd $OLD_DIR
# EOF
