#!/usr/bin/env bash
OLD_DIR=$(pwd)
if [[ -d "$HOME/repos/emacs/" ]]; then
  git fetch --all
  git checkout master
  git pull
else
  cd $HOME/repos
  git clone https://git.savannah.gnu.org/git/emacs.git
  cd $HOME/repos/emacs
fi
echo "****************************************************"
echo "****************************************************"
./autogen.sh
echo "****************************************************"
echo "****************************************************"
./configure --with-native-compilation
echo "****************************************************"
echo "****************************************************"
make NATIVE_FULL_AOT=1 -j$(nproc)
echo "****************************************************"
echo "****************************************************"
sudo make install
cd $OLD_DIR
# EOF
